In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('train.csv')
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404290 entries, 0 to 404289
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            404290 non-null  int64
 1   qid1          404290 non-null  int64
 2   qid2          404290 non-null  int64
 3   question1     404289 non-null  object
 4   question2     404288 non-null  object
 5   is_duplicate  404290 non-null  int64
dtypes: int64(4), object(2)
memory usage: 18.5+ MB

In [6]:
new_df=df.sample(30000)
new_df.head()

,id,qid1,qid2,question1,question2,is_duplicate
133017,133017,212864,212865,Is it really true that there are no such thing...,Are there really no stupid questions?,1
346636,346636,18885,396528,How do I stop dandruff and hairfall?,What is the best method to reduce dandruff?,0
160109,160109,249786,249787,What is a brief history of the relationship be...,History of Great Britain: Has there ever been ...,0
209940,209940,2928,314364,How much does an Ola Mini cab earn on average ...,How much do people who work for taxi companies...,0
120236,120236,195043,37313,What do you do when you hate someone to the core?,What should you do when you hate someone?,1

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000)

In [9]:
ques_df=new_df[['question1','question2']]
questions=list(ques_df['question1'])+list(ques_df['question2'])
q1_arr,q2_arr=np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
tempdf1=pd.DataFrame(q1_arr,index=ques_df.index)
tempdf2=pd.DataFrame(q2_arr,index=ques_df.index)
tempdf=pd.concat([tempdf1,tempdf2],axis=1)
tempdf.head()

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
133017,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
346636,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
160109,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
209940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
120236,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec=TfidfVectorizer(max_features=3000)

In [15]:
Q1_arr,Q2_arr=np.vsplit(vec.fit_transform(questions).toarray(),2)
Tempdf1=pd.DataFrame(Q1_arr,index=ques_df.index)
Tempdf2=pd.DataFrame(Q2_arr,index=ques_df.index)
Tempdf=pd.concat([tempdf1,tempdf2],axis=1)
Tempdf.head()

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
133017,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
346636,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
160109,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
209940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
120236,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
rf1=RandomForestClassifier()

In [20]:
from sklearn.metrics import accuracy_score

In [17]:
X=tempdf.values
y=new_df['is_duplicate'].values

In [23]:
A=Tempdf.values
b=new_df['is_duplicate'].values

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test=train_test_split(A,b,test_size=0.2,random_state=42)

In [19]:
rf1.fit(x_train,y_train)
print(f1_score(y_test,rf1.predict(x_test)))

0.553617386331141

In [21]:
print(accuracy_score(y_test,rf1.predict(x_test)))

0.7398333333333333

In [25]:
rf2=RandomForestClassifier()
rf2.fit(a_train,b_train)
print(f1_score(b_test,rf2.predict(a_test)))

0.5518636232302803

In [26]:
from xgboost import XGBClassifier
xgb1=XGBClassifier()
xgb1.fit(x_train,y_train)
print(f1_score(y_test,xgb1.predict(x_test)))

0.5232726221451286

In [27]:
xgb2=XGBClassifier()
xgb2.fit(a_train,b_train)
print(f1_score(b_test,xgb2.predict(a_test)))

0.5232726221451286